from __future__ import annotations

import torch
from typing import TYPE_CHECKING
from isaaclab.sensors.camera import CameraData

if TYPE_CHECKING:
    from isaaclab.envs import ManagerBasedRLEnv
    from isaaclab.managers import SceneEntityCfg
    

def isaac_camera_data(env: ManagerBasedRLEnv, sensor_cfg: SceneEntityCfg, data_type: str) -> torch.Tensor:
    """Images generated by the usd camera."""
    # extract the used quantities (to enable type-hinting)
    sensor: CameraData = env.scene.sensors[sensor_cfg.name].data

    # return the data
    if data_type == "distance_to_image_plane":
        output = sensor.output[data_type].clone()
        output[torch.isnan(output)] = 0.0
        output[torch.isinf(output)] = 0.0
        return output.permute(0, 3, 1, 2)